DietifyConsult/Models/ConsultantDetailsViewModel.cs
using Entities.Concrete;

namespace DietifyConsult.Models;

public class ConsultantDetailsViewModel
{
    public int ConsultantID { get; set; }
    public string ConsultantName { get; set; }
    public string ConsultantSurName { get; set; }
    public string ConsultantEmail { get; set; }
    public string ConsultantAddress { get; set; }
    public string RatingScore { get; set; }
    public string Specialization { get; set; }
    public string ConsultantImage { get; set; }
    public string PhoneNumber { get; set; }
    public List<Education> Educations { get; set; }
    public List<WorkExperience> WorkExperiences { get; set; }
}

DietifyConsult/Controllers/ConsultantController.cs
using Business.Concrete;
using DataAccess.Concrete.EntityFramework;
using DietifyConsult.Models;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DietifyConsult.Controllers;

[AllowAnonymous]
public class ConsultantController : Controller
{
    private readonly ConsultantManager consultantManager = new(new EfConsultantDal());
    private readonly DietifyConsultContext context = new();

    public IActionResult Index()
    {
        var values = consultantManager.GetAll();
        return View(values);
    }

    public IActionResult Test()
    {
        return View();
    }

    public IActionResult Test2()
    {
        return View();
    }

    [HttpGet]
    public IActionResult ConsultantProfile()
    {
        var userName = User.Identity.Name;
        var userID = context.Clients.Where(x => x.ClientEmail == userName).Select(t => t.ClientID).FirstOrDefault();
        var consultantID = context.Consultants.Where(x => x.ClientID == userID).Select(t => t.ConsultantID).FirstOrDefault();
        var values = consultantManager.GetById(consultantID);
        return View(values);
    }

    [HttpPost]
    public IActionResult ConsultantProfile(Consultant consultant)
    {
        consultantManager.TUpdate(consultant);
        return RedirectToAction("ConsultantProfile", "Consultant");
    }

    public PartialViewResult ConsultantNavbarPartial()
    {
        return PartialView();
    }

    public PartialViewResult ConsultantFooterPartial()
    {
        return PartialView();
    }

    public IActionResult ConsultantDetails(int id)
    {
        ViewBag.i = id;
        TempData["ConsultantId"] = id;
        var values = consultantManager.GetConsultantDetailById(id);

        return View(values);
    }

    [HttpGet]
    public IActionResult TestConsultantProfile()
    {
        var userName = User.Identity.Name;
        var userID = context.Clients.Where(x => x.ClientEmail == userName).Select(t => t.ClientID).FirstOrDefault();
        var consultantID = context.Consultants.Where(x => x.ClientID == userID).Select(t => t.ConsultantID).FirstOrDefault();
        var values = consultantManager.GetById(consultantID);
        return View(values);
    }

    [HttpPost]
    public IActionResult TestConsultantProfile(AddProfileImage profile)
    {
        var existingConsultant = consultantManager.GetById(profile.ConsultantID);
        if (profile.ConsultantImage != null && profile.ConsultantImage.Length > 0)
        {
            var extension = Path.GetExtension(profile.ConsultantImage.FileName);
            var newImageName = Guid.NewGuid() + extension;
            var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/resim/", newImageName);
            using (var stream = new FileStream(location, FileMode.Create))
            {
                profile.ConsultantImage.CopyTo(stream);
            }

            existingConsultant.ConsultantImage = newImageName;
        }

        existingConsultant.ConsultantID = profile.ConsultantID;
        existingConsultant.ConsultantName = profile.ConsultantName;
        existingConsultant.ConsultantSurName = profile.ConsultantSurName;
        existingConsultant.ConsultantEmail = profile.ConsultantEmail;
        existingConsultant.ConsultantAddress = profile.ConsultantAddress;
        existingConsultant.ConsultantStatus = profile.ConsultantStatus;
        existingConsultant.PhoneNumber = profile.PhoneNumber;
        existingConsultant.Price = profile.Price;
        existingConsultant.ConsultantPassword = profile.ConsultantPassword;
        existingConsultant.RatingScore = profile.RatingScore;
        existingConsultant.Specialization = profile.Specialization;
        existingConsultant.ClientID = profile.ClientID;
        consultantManager.TUpdate(existingConsultant);
        return RedirectToAction("TestConsultantProfile", "Consultant");
    }
}
//var query = (from consultant in context.Consultants
//             join education in context.Educations on consultant.ConsultantID equals education.ConsultantID into educationGroup
//             join workExperience in context.WorkExperiences on consultant.ConsultantID equals workExperience.ConsultantID into workExperienceGroup
//             select new
//             {
//                 ConsultantId = consultant.ConsultantID,
//                 FirstName = consultant.ConsultantName,
//                 LastName = consultant.ConsultantSurName,
//                 Email = consultant.ConsultantEmail,
//                 Specialization = consultant.Specialization,
//                 PhoneNumber = consultant.PhoneNumber,
//                 Educations = educationGroup.Select(e => new {
//                     EducationId = e.EducationID,
//                     Degree = e.EducationLevel,
//                     UniversityName = e.UniversityName,
//                     StartDate = e.UniversityGraduateHistory,
//                     EndDate = e.UniversityEndDate
//                 }).ToList(),
//                 WorkExperiences = workExperienceGroup.Select(w => new {
//                     WorkExperienceId = w.WorkExperienceID,
//                     Company = w.CompanyName,
//                     Continues = w.Continues,
//                     StartDate = w.StartingDate,
//                     EndDate = w.EndDate
//                 }).ToList()
//             }).FirstOrDefault(c => c.ConsultantId == id);

//    ViewBag.i = id;
//            var values = consultantManager.GetConsultantById(id);

//    var education = context.Educations.FirstOrDefault(x => x.ConsultantID == id);
//    ViewBag.UniversityName = education?.UniversityName;
//			ViewBag.UniversityGraduateHistory = education?.UniversityGraduateHistory.ToString("yyyy");
//			ViewBag.UniversityEndDate = education?.UniversityEndDate.ToString("yyyy");
//            ViewBag.EducationLevel = education?.EducationLevel;

//            var workExperience = context.WorkExperiences.FirstOrDefault(x => x.ConsultantID == id);
//    ViewBag.CompanyName = workExperience?.CompanyName;
//            ViewBag.StartingDate = workExperience?.StartingDate.ToString("yyyy");

//            var result = context.WorkExperiences.Where(x => x.ConsultantID == id).Select(y => y.EndDate).FirstOrDefault();
//            if(result != null)
//            {
//                ViewBag.EndDate=result;
//            }
//            else
//{
//    ViewBag.EndDate = "Devam Ediyor. ";
//}
//return View(values);

DietifyConsult/Controllers/TestController.cs
using DataAccess.Concrete.EntityFramework;
using DietifyConsult.Models;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace DietifyConsult.Controllers
{
    public class TestController : Controller
    {
        DietifyConsultContext context = new DietifyConsultContext();

        public IActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialDetails(int id, DateTime? selectedDate = null)
        {
            var dietitian = context.Consultants.Include(d => d.Appointments)
                .FirstOrDefault(d => d.ConsultantID == id);

            if (dietitian == null)
            {
                return PartialView();
            }

            DateTime startDate = selectedDate ?? DateTime.Today; // Use selectedDate if provided, otherwise default to today
            DateTime endDate = startDate.AddDays(14);

            var recentAppointments = dietitian.Appointments
                .Where(a => a.AppointmentDateTime >= startDate && a.AppointmentDateTime <= endDate)
                .ToList();

            var availableTimesByDay = GetAvailableTimes(recentAppointments, startDate, endDate);

            var model = new DietitianDetailsViewModel
            {
                Consultant = dietitian,
                AvailableTimesByDay = availableTimesByDay,
                SelectedDate = selectedDate
            };

            return PartialView(model); // Partial view olarak geri dön
        }
        public IActionResult Details(int id, DateTime? selectedDate = null)
        {
            var dietitian = context.Consultants.Include(d => d.Appointments)
                .FirstOrDefault(d => d.ConsultantID == id);

            if (dietitian == null)
            {
                return NotFound();
            }

            DateTime startDate = selectedDate ?? DateTime.Today; // Use selectedDate if provided, otherwise default to today
            DateTime endDate = startDate.AddDays(14);

            var recentAppointments = dietitian.Appointments
                .Where(a => a.AppointmentDateTime >= startDate && a.AppointmentDateTime <= endDate)
                .ToList();

            var availableTimesByDay = GetAvailableTimes(recentAppointments, startDate, endDate);

            var model = new DietitianDetailsViewModel
            {
                Consultant = dietitian,
                AvailableTimesByDay = availableTimesByDay,
                SelectedDate = selectedDate
            };

            return View(model); // Partial view olarak geri dön
        }

        private Dictionary<DateTime, List<TimeSpan>> GetAvailableTimes(ICollection<Appointment> appointments, DateTime startDate, DateTime endDate)
        {
            var availableTimesByDay = new Dictionary<DateTime, List<TimeSpan>>();

            for (var date = startDate.Date; date <= endDate.Date; date = date.AddDays(1))
            {
                var availableTimes = new List<TimeSpan>();
                var existingAppointments = appointments.Where(a => a.AppointmentDateTime.Date == date).ToList();

                for (var time = new TimeSpan(9, 0, 0); time < new TimeSpan(17, 0, 0); time = time.Add(TimeSpan.FromHours(1)))
                {
                    if (!existingAppointments.Any(a => a.AppointmentDateTime.TimeOfDay == time))
                    {
                        availableTimes.Add(time);
                    }
                }

                availableTimesByDay[date] = availableTimes;
            }

            return availableTimesByDay;
        }
    }
}

DietifyConsult/Views/Consultant/ConsultantDetails.cshtml
@model IEnumerable<Entities.Concrete.Consultant>
@{
    ViewData["Title"] = "ConsultantDetails";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}
<body>
    @*    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    *@    <!--//banner-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <section class="banner-bottom">
        <!--/blog-->
        <div class="container">
            <div class="row">
                <!--left-->
                <div class="col-lg-8 left-blog-info-w3layouts-agileits text-left">
                    @foreach (var item in Model)
                    {
                        <div class="blog-grid-top">
                            <div class="b-grid-top">
                                <div class="circle-image">
                                    <a>
                                        <img style="width: 250px; height:270px;" src="~/resim/@item.ConsultantImage" class="img-fluid" alt="">
                                    </a>
                                </div>
                            </div>
                            <span style="display: flex; align-items: center;">
                                <i class="fas fa-star" style="color: #f9c72e; margin-right: 5px;"><span> @item.RatingScore &nbsp</span></i>
                                <h3>@item.ConsultantName @item.ConsultantSurName - Seans Ücreti: @item.Price ₺ </h3>

                            </span>
                            <hr>
                            <p class="consultant-details">

                                <h5>Eğitim Bilgileri</h5>
                                <br>
                                <ul>
                                    @foreach (var education in item.Educations)
                                    {
                                        <li style="color:#a0a1a5">
                                            @education.EducationLevel - @education.UniversityName &nbsp @education.UniversityGraduateHistory.Year - @education.UniversityEndDate.Year
                                        </li>
                                    }
                                </ul>
                                <br>
                                <hr>
                                <h5>İş Deneyimleri</h5>
                                <br>
                                <ul>
                                    @foreach (var workExperiences in item.WorkExperiences)
                                    {
                                        <li style="color:#a0a1a5">
                                            @workExperiences.CompanyName &nbsp @workExperiences.StartingDate.Year - @(workExperiences.EndDate != null ? workExperiences.EndDate.Value.ToString("yyyy") : "Devam ediyor.")
                                        </li>
                                    }
                                </ul>
                                <br>
                                <hr>
                                <h5>Uzmanlık Alanı</h5>
                                <br>
                                @{
                                    string[] specializations = item.Specialization.Split(',');
                                }

                                @if (specializations.Any())
                                {
                                    <ul>
                                        @foreach (var specialization in specializations)
                                        {
                                            <li style="color:#a0a1a5">@specialization.Trim()</li>
                                        }
                                    </ul>
                                }
                            </p>
                            <hr>
                            <h5>İletişim Bilgileri</h5>
                            <br>
                            <ul class="icon-list">
                                <li><i class="fas fa-phone"></i> Telefon Numarası: @item.PhoneNumber</li>
                                <li><i class="fas fa-envelope"></i> Email Adresi: @item.ConsultantEmail</li>
                            </ul>
                            <br>
                            <a href="/Consultant/Index" class="btn btn-primary read-m">Diyetisyen Listesi</a>
                            <a href="/IntegrationAppointment/Details/@item.ConsultantID" class="button">Randevu Al</a>

                            @*                            <div class="modal fade" id="myModal" role="dialog" data-url='@Url.Action("PartialDetails", "Test", new { id = item.ConsultantID })'></div>
                        *@
                        </div>

                    }
                    @await Component.InvokeAsync("ConsultantCommentList",new { id = ViewBag.i })
                    @*					@await Html.PartialAsync("~/Views/BlogComment/CommentListByBlog.cshtml")
                    *@					@await Html.PartialAsync("~/Views/ConsultantComment/PartialAddConsultantComment.cshtml")
                    @*                    @await Component.InvokeAsync("ConsultantCommentAdd",new { id = ViewBag.i })
                    *@

                </div>

                <!--//left-->
                <!--right-->
                <aside class="col-lg-4 agileits-w3ls-right-blog-con text-right">
                    <div class="right-blog-info text-left">
                        <h4>Sitemize abone ol</h4>

                        @await Html.PartialAsync("~/Views/Blog/PartialSubscribe.cshtml")

                        @await Component.InvokeAsync("BlogTopWeek")

                        @await Component.InvokeAsync("RecentBlog")

                    </div>

                </aside>
                <!--//right-->
            </div>
        </div>
    </section>
    <style>
        .circle-image {
            position: relative; /* Enable layering for overlay effects */
            display: flex;
            align-items: center; /* Vertically center image and info */
            width: 250px; /* Adjust image container width as needed */
            height: 250px; /* Adjust image container height as needed */
        }

            .circle-image img {
                width: 100%; /* Image fills container width */
                height: auto; /* Image maintains aspect ratio */
                border-radius: 50%; /* Circular image */
                box-shadow: 0 0 5px rgba(0, 0, 0, 0.2); /* Subtle shadow for depth */
            }



        .consultant-image-wrapper:hover {
            background-color: rgba(0, 0, 0, 0.5); /* Darken background on hover */
        }

        .consultant-details-excerpt {
            font-size: 0.8rem; /* Adjust font size for a concise overview */
            margin-top: 5px; /* Add spacing above bio */
        }

        .button {
            background-color: black;
            color: white;
            padding: 8.2px 20px;
            border: none;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

            .button:hover {
                background-color: #01cd74;
                color: black
            }

        .icon-list li {
            color: #a0a1a5;
            display: flex;
            align-items: center;
        }

            .icon-list li i {
                margin-right: 10px;
            }
    </style>
    @*    <script type="text/javascript">
    $(document).ready(function () {

    $('.button').click(function () {

    var url = $('#myModal').data('url');
    $.get(url, function (data) {

    $("#myModal").html(data);
    $("#myModal").modal('show');
    });
    });

    });
    </script>*@
</body>

DietifyConsult/Views/Consultant/ConsultantFooterPartial.cshtml
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Bitirme Ödevi © Rabia Nur Kavi 2024</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">
            <a href="https://www.github.com/rabianurkavi/" target="_blank">Github </a>
        </span>
    </div>
</footer>

DietifyConsult/Views/Consultant/ConsultantNavbarPartial.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        @await Component.InvokeAsync("ConsultantNavbarName");
        <li class="nav-item">
            <a class="nav-link" href="~/Consultant/TestConsultantProfile">
                <span class="menu-title">Profilim</span>
                <i class="mdi mdi-account menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Appointment/ConsultantByAppointment">
                <span class="menu-title">Tüm Randevular</span>
                <i class="mdi mdi-calendar-range menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Appointment/PendingAppointment">
                <span class="menu-title">Bekleyen Randevular</span>
                <i class="mdi mdi-calendar-clock menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Appointment/ConfirmedAppointment">
                <span class="menu-title">Onaylanan Randevular</span>
                <i class="mdi mdi-calendar-plus menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Appointment/ListCompletedAppointment">
                <span class="menu-title">Tamamlanan Randevular</span>
                <i class="mdi mdi-calendar-multiple-check menu-icon"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogListByConsultant/">
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogAdd/">
                <span class="menu-title">Yeni Blog</span>
                <i class="mdi mdi-format-list-triangle menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Message/Inbox">
                <span class="menu-title">Gelen Mesajlar</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Message/SendBox">
                <span class="menu-title">Giden Mesajlar</span>
                <i class="mdi mdi-message-reply-text menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Notification/Index/">
                <span class="menu-title">Duyurular</span>
                <i class="mdi mdi-bell-ring menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="~/Blog/Index">
                <span class="menu-title">Siteye Git</span>
                <i class="mdi mdi-table-large menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="~/Consultant/TestConsultantProfile">
                <span class="menu-title">Ayarlar</span>
                <i class="mdi mdi-settings menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="~/Login/LogOut">
                <span class="menu-title">Çıkış Yap</span>
                <i class="mdi mdi-door-closed menu-icon"></i>
            </a>
        </li>
    </ul>
</nav>

DietifyConsult/Views/Consultant/ConsultantProfile.cshtml
@model Entities.Concrete.Consultant
@{
    ViewData["Title"] = "ConsultantProfile";
    Layout = "~/Views/Shared/_ConsultantLayout.cshtml";
}

@using (Html.BeginForm("ConsultantProfile", "Consultant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <style>
        body {
            background-color: #f7f7f7; /* Light gray background */
        }

        h1 {
            color: #2c3e50; /* Dark blue heading */
        }

        label {
            color: #2c3e50; /* Dark blue labels */
        }

        .form-control {
            border: 1px solid #bdc3c7; /* Light gray border */
        }

        .btn-primary {
            background-color: #27ae60; /* Green primary button */
            border: none;
            transition: background-color 0.3s ease; /* Smooth transition */
        }

            .btn-primary:hover {
                background-color: #219653; /* Darker green on hover */
            }

        .fa-star {
            color: #f39c12; /* Orange star */
        }

        .validation-message {
            color: red; /* Red validation messages */
        }
        /* Profil fotoğrafı çerçeve */
        .profile-picture {
            border: 5px solid #8558a6;
            overflow: hidden;
            width: 200px;
            height: 200px;
            margin-bottom: 20px;
        }

            .profile-picture img {
              
                object-fit: cover;
            }

    </style>

    <br/>
    @Html.Label("Profil Fotoğrafı")
    <br/>
    <div class="profile-picture">
        @if (!string.IsNullOrEmpty(Model.ConsultantImage))
        {
            <img src="~/resim/@Model.ConsultantImage" alt="Profil Fotoğrafı" class="img-fluid"/>
        }
    </div>
    <span class="fa fa-star">@Model.RatingScore</span>
    <small style="color: orange;">(Değerlendirme)</small>
    <br/>
    @Html.ValidationMessageFor(x => x.ConsultantImage, "", new { @class = "validation-message" })
    <br/>
    @Html.Label("İsim")
    @Html.TextBoxFor(x => x.ConsultantName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.ConsultantName, "", new { @class = "validation-message" })
    <br/>
    @Html.Label("Soy İsim")
    @Html.TextBoxFor(x => x.ConsultantSurName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.ConsultantSurName, "", new { @class = "validation-message" })
    <br/>
    @Html.Label("Uzmanlık Alanı")
    @Html.TextBoxFor(x => x.Specialization, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Specialization, "", new { @class = "validation-message" })
    <br/>
    @Html.Label("Telefon Numarası")
    @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.PhoneNumber, "", new { @class = "validation-message" })
    <br/>
    @Html.Label("Email")
    @Html.TextBoxFor(x => x.ConsultantEmail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.ConsultantEmail, "", new { @class = "validation-message", type = "email" })
    <br/>
    @Html.Label("Yaşadığı Şehir")
    @Html.TextBoxFor(x => x.ConsultantAddress, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.ConsultantAddress, "", new { @class = "validation-message" })
    <br/>
    @Html.Label("Seans Ücreti")
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Price, "", new { @class = "validation-message" })
    <br/>
    @Html.Label("Şifre")
    @Html.TextBoxFor(x => x.ConsultantPassword, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.ConsultantPassword, "", new { @class = "validation-message" })
    <br/>
    <br/>
    <br/>
    @Html.HiddenFor(x => x.ConsultantID)
    @Html.HiddenFor(x => x.ClientID)
    @Html.HiddenFor(x => x.ConsultantImage)
    @Html.HiddenFor(x => x.RatingScore)
    @Html.HiddenFor(x => x.ConsultantStatus)

    <button class="btn btn-primary">Değişiklikleri Kaydet</button>
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">

DietifyConsult/Views/Consultant/Index.cshtml
@model List<Entities.Concrete.Consultant>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Diyetisyenler</h3>
        <div class="inner-sec">
            <!--left-->
            <div class="left-blog-info-w3layouts-agileits text-left">
                <div class="row">
                    @foreach (var item in Model)
                    {
                        <div class="col-lg-4 card">
                            <a href="~/Consultant/ConsultantDetails/@item.ConsultantID">
                                <img style="width:350px; height:350px" src="~/resim/@item.ConsultantImage" class="card-img-top img-fluid" alt="">
                            </a>
                            <a href="~/Consultant/ConsultantDetails/@item.ConsultantID" class="btn btn-secondary">Diyetisyeni İncele</a>

                            <div class="card-body">
                                <ul class="blog-icons my-4">
                                    <li>
                                        <a href="#">
                                            <i class="fas fa-lira-sign"></i> @item.Price
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fas fa-star"></i> @item.RatingScore
                                        </a>
                                    </li>

                                </ul>
                                <h5 class="card-title">
                                    <a href="Consultant/ConsultantDetails/@item.ConsultantID">@item.ConsultantName @item.ConsultantSurName </a>
                                </h5>
                                <p class="card-text mb-3">@item.Specialization </p>
                                <a href="/IntegrationAppointment/Details/@item.ConsultantID" class="btn btn-primary read-m">Randevu Al</a>
                            </div>
                        </div>
                    }
                </div>
                <!--//left-->
            </div>
        </div>
    </div>
</section>

DietifyConsult/Views/Consultant/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/_ConsultantLayout.cshtml";
}

<h1>Test</h1>